# docker-compose -f ./docker-compose.dev.yml up --build
version: "3.9"
services:
  web_dev:
    build:
      context: ./pages/leonardo-social-platform/
      dockerfile: dev.Dockerfile
    container_name: "web_dev"
    ports:
      - "3000:3000"
    depends_on:
      - database_dev
    environment:
      WAIT_HOSTS: db:27017
      WAIT_HOSTS_TIMEOUT: 120
    restart: always

    volumes:
      - ./pages/leonardo-social-platform:/usr/src/app/

    # alias db = database_dev
    links:
      - "database_dev:db"
  database_dev:
    image: "mongo"
    container_name: "mongo-dev"

    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password

    ports:
      - "27017:27017"
    volumes:
      - ./initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongodb:/data/db

    command: [--auth]
    restart: always

    secrets:
      - db_root_username
      - db_root_password
  # redis:
  #   container_name: "redis-dev"
  #   image: "redis:6.2.1-alpine"
  #   ports:
  #     - "6379:6379"

secrets:
  db_root_username:
    file: ./data/mongodbAuth/user
  db_root_password:
    file: ./data/mongodbAuth/pwd
