# docker-compose -f ./docker-compose.yml up --build --remove-orphans
version: "3.9"
services:
  web:
    build:
      context: ./pages/leonardo-social-platform/
      dockerfile: dist.Dockerfile
    container_name: "web"
    depends_on:
      - database
    environment:
      WAIT_HOSTS: db:27017
      WAIT_HOSTS_TIMEOUT: 120
    restart: always

    # alias db = database
    links:
      - "database:db"

  database:
    image: mongo:latest
    container_name: mongo

    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/db_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    volumes:
      - ./initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongodb:/data/db

    command: [--auth]
    restart: always

    secrets:
      - db_root_username
      - db_root_password
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - "web:web"

    restart: always

secrets:
  db_root_username:
    file: ./data/mongodbAuth/user
  db_root_password:
    file: ./data/mongodbAuth/pwd
