version: "3.9"
services:
  web:
    build: ./pages/leonardo-social-platform/
    container_name: "web"
    ports:
      - "3000:3000"
  database:
    image: "mongo"
    container_name: "mongo"

    # ports:
    #   - "27017:27017"
    volumes:
      - ./initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/mongodb:/data/db
  # redis:
  #   container_name: "redis"
  #   image: "redis:6.2.1-alpine"
  #   # ports:
  #   #   - "6379:6379"
